[package]
authors = ["Facebook", "Alex Choi"]
categories = ["rust-patterns"]
description = "Comparison for &dyn types"
documentation = "https://docs.rs/blueprint-cmp-any"
edition = "2021"
license = { workspace = true }
name = "blueprint-cmp-any"
repository = { workspace = true }
version = "0.8.1"
